name: Create and Update Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Changelog
        id: changelog
        run: |
          # Generate changelog here
          echo "Changelog content" > changelog.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.12
          release_name: Release v1.0.12
          body: |
            $(cat changelog.txt)

      - name: Update Release Tag
        if: success()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github } = require('@actions/github');
            const releaseTag = 'releases'; // Specify the tag name here
            const repo = github.context.repo;

            // Create a new tag reference for the release
            github.git.createRef({
              ...repo,
              ref: `refs/tags/${releaseTag}`,
              sha: github.context.payload.release.target_commitish
            });
