# Release notes configuration file

# Define the categories for your release notes
categories:
  - name: Bug Fixes
    label: bug
  - name: New Features
    label: feature
  - name: Enhancements
    label: enhancement

# Define the labels associated with each category
labels:
  bug:
    color: "d73a4a"  # Red
  feature:
    color: "0075ca"  # Blue
  enhancement:
    color: "a2eeef"  # Light Blue

# Define additional metadata fields for your release notes
metadata:
  author: "{{ author }}"
  date: "{{ date }}"
  version: "{{ version }}"
