name: Notify on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Notify via Slack
        uses: Ilshidur/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "Pull request <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}> was merged by ${{ github.event.pull_request.merged_by.login }} into main branch."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
